version: "2"
networks:
  backend:
    external:
      name: caddy_backend

services:
  landingpage:
    image: busybox
    working_dir: /www
    restart: always
    tty: true
    stdin_open: true
    read_only: true
    entrypoint: httpd
    command: -f -v -p 80 -h .
    expose:
      - 80
    volumes:
      - ./www:/www
    networks:
      - backend
